aws-greengrass/aws-greengrass-log-manager

src/integrationtests/java/com/aws/greengrass/logmanager/LogManagerTest.java, src/integrationtests/java/com/aws/greengrass/logmanager/SpaceManagementTest.java, src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java, src/test/resources/com/aws/greengrass/logmanager/testlogs2.log
If the log message is in JSON format, then use the timestamp from the the JSON object.
If the log message is in TEXT format, then get the timestamp using a regex. The timestamp should be at the very beginning of the log line.
Currently we are sending the timestamp of the CW log events as the time of the upload which is different from the logs timestamp.
Added unit tests.
**Checklist:**
=> fix: Send the correct timestamp to CloudWatch when uploading logs.

src/integrationtests/java/com/aws/greengrass/logmanager/LogManagerTest.java, src/integrationtests/java/com/aws/greengrass/logmanager/SpaceManagementTest.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java
The integration tests were broken after this [change](https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/813) in the Nucleus. Also fix flaky unit test by using the correct time zone.
**Checklist:**
=> test: Use the correct IoT endpoints and region in tests after adding validation in Nucleus

src/integrationtests/java/com/aws/greengrass/logmanager/LogManagerTest.java, src/integrationtests/java/com/aws/greengrass/logmanager/util/LogFileHelper.java, src/integrationtests/resources/com/aws/greengrass/logmanager/smallPeriodicIntervalOnlyReqUserComponentConfig.yaml, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
https://github.com/aws-greengrass/aws-greengrass-log-manager/issues/41
Currently, the customers need to provide the location of the log files for an installed component in GGV2. This change will help the customer to just specify the name of the component if the component is using the logging framework provided by the Nucleus.
This would help the customer to just specify the component name in the Log Manager configuration and then the Log Manager component will use the logger config to get the file name that the component is logging to along with the location of those log files.
Added unit and integration tests.
**Any additional information or context required to review …
=> improvement: Add logic to use logger config if available for component configuration

src/main/java/com/aws/greengrass/logmanager/CloudWatchLogsUploader.java, src/main/java/com/aws/greengrass/logmanager/model/CloudWatchAttemptLogInformation.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchLogsUploaderTest.java
Sorts log events by timestamp because CloudWatch requires that they are in chronological order.
**Checklist:**
=> fix: sort log events by timestamp for CloudWatch 400 error

src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java
Remove deployment group names from log streams.
The current log stream format is `/{date}/thing/thinggroup/{group1}/thinggroup/{group2}/thing/{thingname}` 
If there is no group present the local deployment group name hardcoded in Nucleus gets added.
The new log stream format will be /{date}/thing/{thingname}
Adding groups to log stream names has been causing us issues.
Recently we had to fix an issue about characters from group arns not being supported in log stream names by CW.
Currently we're dealing with an issue where we cannot properly predict what log stream name will be when multiple deployments happen to the device for a component one after the other from the cloud or from cli
If the list and …
=> Remove deployment group names from log streams

pom.xml, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
When `diskLimit` option is set too low, LogManager was deleting the active log file. This change will prevent us from deleting the active log.
**Checklist:**
=> fix: do not delete the active log file

src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
Cloudwatch requires that any batch upload does not exceed a time span of 24 hours. This change splits out each 24 hour batch in order to respect that requirement.
**Checklist:**
=> fix: respect 24 hour time span limits for CW upload

src/main/java/com/aws/greengrass/logmanager/CloudWatchLogsUploader.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchLogsUploaderTest.java
When sending emf formatted JSON logs the log-manager does not apply the `x-amzn-logs-format: json/emf` header for cloud watch to process the emf logs [ref](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html)
Adds the emf header based on new isEmf field in the `ComponentLogConfiguration`.  
see issue
unit tests - still WIP
**Checklist:**
=> feat: add cw emf logging support - WIP

src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/main/java/com/aws/greengrass/logmanager/PositionTrackingBufferedReader.java
Attempt to fix #72 
Use a custom override of `BufferedReader` to buffer the log file contents in order to read more IO efficiently than `RandomAccessFile`. Needed to implement it the way that I have so that we can still know how many bytes we've read and then seek to that point in the file. 
**Checklist:**
=> fix: use BufferedReader to read log files efficiently

src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/main/java/com/aws/greengrass/logmanager/CloudWatchLogsUploader.java, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
Some small fixes including quoting the filenames before inserting them into our predefined regex. Also fixes which regex is used in the space management thread; it was using the multiline regex instead of the filename regex.
**Checklist:**
=> fix: use correct matcher in space management, remove useless logs

README.md, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/logmanager/configsDifferentFromDefaults.yaml, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
Fixing bugs so that when logFileRegex or periodicUploadIntervalSec config key is removed, the value is reset to the correct default.
Also adding testing for correct reset values for other component config keys
**Checklist:**
=> fix: component config reset bug

README.md, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/logmanager/configsDifferentFromDefaults.yaml, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
Fixing bug, so that when periodicUploadIntervalSec or logsUploaderConfiguration config keys are removed via reset, and subsequently replaced, then the new values will be used.
**Checklist:**
=> fix: bug when config values are replaced after a reset

src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java
CloudWatch PutLogEvents API fails validation when a log event has an empty message, this change skips any empty messages so other logs in the batch can be uploaded
This causes the batch upload to fail while empty messages are of no value to users
New unit test
**Checklist:**
=> fix: skip empty log messages that fail CW validation

src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java
Jackson `ObjectMapper::readValue` might return null when handling log message like `"null"`, which throws a NullPointerException with `Optional.of`. 
Handle it by replacing with `Optional.ofNullable`.
Fixes NPE.
Added unit test.
**Checklist:**
=> fix: handles NPE when an invalid log message is processed

src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/main/java/com/aws/greengrass/logmanager/model/LogFile.java, src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java, src/test/java/com/aws/greengrass/logmanager/model/LogFileGroupTest.java, src/test/java/com/aws/greengrass/logmanager/util/TestUtils.java
#51 
Add the logFileGroup update to the latest directory, thus grab information even log rotation happens during uploading.
**Checklist:**
=> feat: enable logFileGroup update with latest directory

src/main/java/com/aws/greengrass/logmanager/model/LogFile.java
Adds new hashing function which computes hash given a open file rather than opening the file, computing hash, then closing the file. This is needed to avoid TOCTOU races where the log can rotate between us computing the hash and uploading it.
**Checklist:**
=> feat: new hash function

src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
Create hardlinks directory inside of the work folder of the log manager component. This will be used to store component log file hardlinks to avoid data loss due to file rotation.  
**Checklist:**
=> feat: create a dir inside work folder to store the log file hardlinks

src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java, src/test/java/com/aws/greengrass/logmanager/model/LogFileGroupTest.java
Pass ComponentLogConfiguration object to LogFileGroup instead of passing individual params. This will help us write better log to the files by using the info from the ComponentLogConfiguration. 
**Checklist:**
=> refactor: pass ComponentLogConfiguration object to LogFileGroup

src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/main/java/com/aws/greengrass/logmanager/exceptions/InvalidLogGroupException.java, src/main/java/com/aws/greengrass/logmanager/model/LogFile.java, src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
Created hardlinks for log file when collecting the log files to process and upload. 
This can prevent data loss due to rotation as the hardlink still persists even when the source log file is deleted. 
Taken mostly from: https://github.com/aws-greengrass/aws-greengrass-log-manager/pull/136
**Checklist:**
=> feat: use hardlinks of log file during processing

src/main/java/com/aws/greengrass/logmanager/model/LogFile.java, src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java
Fixes the `isActive` method on the `LogFileGroup` so that if the active file has rotated by the time we check if it is the active file, then we return false so it doesn't get set as the currently processing file.
Would cause an active file that just got rotated to be processed twice.
Manual tests
=> feat: return false if the original active file has rotated

src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java
We can not create hard links for log files being created on a volume separate to the one greengrass is running on. In the scenario where that happens we want to rollback and only upload the rotated log files and stop processing the active file. Effectively working how it used to work before
Ensure we are not breaking customers that have a setup where they track log files being written to a separate volume.
Manual tests, we will cover with unit and integration tests but we have to make more changes to make this scenarios more easily testable.
=> feat: rollback to only uploading rotated files if we fail to create hardlinks

src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/main/java/com/aws/greengrass/logmanager/model/LogFile.java, src/test/java/com/aws/greengrass/logmanager/model/LogFileTest.java, src/test/java/com/aws/greengrass/logmanager/util/TestUtils.java
Hardlinks can't return the source path they are tracking. When we delete a file we want to ensure we are deleting the correct file and not the file path the hardlink got originally created with.
We might end up not deleting the files or deleting the wrong file.
Unit tests
=> feat: update delete after upload

src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java, src/test/java/com/aws/greengrass/logmanager/model/LogFileGroupTest.java, src/test/java/com/aws/greengrass/logmanager/model/LogFileTest.java, src/test/java/com/aws/greengrass/logmanager/util/TestUtils.java
Add a few unit tests for the LogFile and the LogFileGroup and also made it so the log group does not return files that do not have a hash so we don't have to be sprinkling that logic around the codebase
Encapsulate logic related to which files should be processed.
Unit tests
=> refactor: cleanup and add some unit tests for log group and log file

uat/src/main/java/com.aws.greengrass/FileSteps.java, uat/src/main/resources/greengrass/features/log-manager-1.feature
filestep do not have the part to write logs for non Nucleus components
**Description of changes:** 
fix file steps
to write logs for custom component
by creating new configuration for UserComponentA
**Checklist:**
=> fix: file steps

uat/pom.xml
Now that we have made some fixes to OTF so that it could be built in windows, the version OTF builds as is version 0.1.0. We are changing the version to that one so that we can reference the local version of OTF when developing tests so that changes made in OTF can be reflected immediately when added as a dependency.
Pull OTF local version instead of the one on a maven repo
=> chore: point otf standalone dependency to 0.1.0

uat/src/main/java/com.aws.greengrass/FileSteps.java, uat/src/main/resources/greengrass/features/log-manager-1.feature
Now that we can reference the locally installed version of OTF there are a few steps that we were missing that are available. This PR just adds those steps in to the tests the were already ported.
Other changes:
* Fix checkstyle violations
* Remove bad step
Ensures we wait first for the LogManager to be running
=> fix: add missing steps

uat/src/main/java/com.aws.greengrass/FileSteps.java, uat/src/main/resources/greengrass/features/log-manager-1.feature
Port test Logmanager-T1-b
As a customer I can configure the logs uploader component using a componentLogsConfigurationMap and logs are uploaded to CloudWatch
**Checklist:**
=> Feat port test t1b

uat/pom.xml, uat/src/main/java/com.aws.greengrass/FileSteps.java, uat/src/main/resources/greengrass/features/log-manager-1.feature
LogManager-1-T4: As a developer, logs uploader will handle network interruptions gracefully and upload logs from the last uploaded log after network resumes
**Checklist:**
=> Feat port t4

uat/pom.xml
OTF version got bumped to 1.0.0-SNAPSHOT when open sourced. This PR just changes the version so that we can build OTF locally and it references the correct and also so that it fetched the new version from the maven reposittory
=> chore: update otf dependency to open source version

pom.xml
Excludes the contents inside the uat folder from being included on the final uber jar.
Avoid bloating the project size when uats grow
=> chore: exclude uat folder from uber jar

src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/util/LogFileHelper.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/logmanager/smallSpaceManagementPeriodicIntervalConfig.yaml
There was an issue where someone removed the diskSpaceLimit configuration from their configuration and the Log Manager was still deleting files. I wrote an integration test to validate if there was a real issue (which is all this PR has, a new integ test)
After some research and noticing it was not an issue with the log manager code (hence the integ test). I pinpointed the root cause to it being that removing a configuration value using merge from the AWS console doesn't cause the configuration from being removed in the component. Customers must use reset when wanting to delete values from their configuration
Just an integration test
Covers a scenario not previously tested
=> test: cover scenario where diskSpaceLimit config is removed

.gitignore, gdk-config.json, recipe.yaml, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/logmanager/smallSpaceManagementPeriodicIntervalConfig.yaml, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java, src/main/java/com/aws/greengrass/logmanager/services/DiskSpaceManagementService.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java, src/test/java/com/aws/greengrass/logmanager/model/LogFileGroupTest.java, src/test/java/com/aws/greengrass/logmanager/services/DiskSpaceManagementServiceTest.java
This changes simplify the disk space management functionality to avoid some of the pitfalls that have bitten us in the past. 
The existing code:
* Competes with uploads and could delete a file while it is uploaded (sure, we could have added synchronization and locks but complexity comes at a cost)
* Deletes the active log file depending on the configuration
* Uses watchers and re-dispatches a thread when there are failures
* Competes with the delete after cloud upload functionality
* Does not deal with file rotation, it can end up deleting the wrong file
The new code operates on the same upload thread and frees space after the uploads are complete and only clears files that have not been processed. It could come at a tiny cost addition of deleting files but if …
=> feat: simplify space management

.github/workflows/uat.yaml, uat/codebuild/uat_linux_buildspec.yaml, uat/testing-features/src/main/resources/greengrass/features/log-manager-1.feature
Adds workflow to run the uats on codebuild
Extra testing layer to perform e2e tests before merging
Codebuild flow passing
=> chore: run lm uats on codebuild pipeline

uat/testing-features/pom.xml
OTF 1.1.0 is released, so cutting this PR to adapt to use 1.1.0.
**Checklist:**
=> chore: adapt to OTF 1.1.0

src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerConfigTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/logmanager/doNotDeleteFilesAfterUpload.yaml, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/main/java/com/aws/greengrass/logmanager/model/ProcessingFiles.java, src/main/java/com/aws/greengrass/logmanager/services/DiskSpaceManagementService.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
To fix an issue where customer wrote to multiple active files within a same group we started tracking all the files on a cache that is written into disk. Items get evicted based on time, if the entry has not been modified in more that one day we evict it.
We are not removing entries from the cache once files get deleted though. This PR makes it so that entries for files that have been deleted get removed from the cache, resulting in less memory and disk space consumption.
Avoid memory consumption spikes and potential OOM errors for high write frequency use cases.
Integration tests. Will follow up with a UAT
=> fix: free up cache space when files get deleted

src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, uat/custom-components/src/main/java/com/aws/greengrass/artifacts/LogGenerator.java, uat/testing-features/src/main/java/com/aws/greengrass/steps/CloudWatchSteps.java, uat/testing-features/src/main/resources/greengrass/features/log-manager-1.feature
When there are more than 10000 logs to upload, then log manager uploads those logs in multiple attempts where each attempt uploads a maximum of 10000 logs. (CW limit for max log events per API is 10000)
**Checklist:**
=> test: add a UAT to verify max log event limit

src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java, uat/testing-features/pom.xml, uat/testing-features/src/main/resources/greengrass/features/log-manager-1.feature
AWS CloudWatch PutLogEvents API has a limit of 10,000 log events per request.
Documentation link: [Array Members: Minimum number of 1 item. Maximum number of 10000 items](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html#:~:text=array%20members%3A%20minimum%20number%20of%201%20item.%20maximum%20number%20of%2010000%20items.).
Currently, log manager component tries to upload all the log events without validating their size. Adding an extra check to validate the log events size before adding a new log event. 
This is an edge case where there are more than 10,000 logs to upload, with each log event size less than the 1024*256 - 8-26 bytes limit and the total batch size less than 1024*1024 bytes. …
=> fix: validate cw log events size  before uploading

src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/util/LogFileHelper.java, src/integrationtests/resources/com/aws/greengrass/integrationtests/logmanager/smallPeriodicIntervalOnlyReqUserComponentConfig.yaml, src/integrationtests/resources/com/aws/greengrass/integrationtests/logmanager/smallPeriodicIntervalSystemComponentConfig.yaml, src/integrationtests/resources/com/aws/greengrass/integrationtests/logmanager/smallPeriodicIntervalUserComponentConfigNoMultiline.yaml, src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java
- Performance: skip json parsing if the log line doesn't start with `{`
- Update the multiline pattern to split by date stamp so that stacktraces will be correctly associated with the log that emitted them.
Adds proper testing for stacktrace collection which didn't exist before.
**Checklist:**
=> fix: update default multiline pattern to properly collect stacktraces

src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerConfigTest.java, src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/main/java/com/aws/greengrass/logmanager/model/CloudWatchAttemptLogInformation.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchLogsUploaderTest.java, uat/testing-features/src/main/java/com/aws/greengrass/resources/CloudWatchLogsLifecycle.java, uat/testing-features/src/main/java/com/aws/greengrass/steps/CloudWatchSteps.java
We need the log events to be sorted at the end to upload and we're checking ever time we insert into the log batch that the batch is all within 24 hours which requires us to get the earliest time from the batch. This turned out to be very costly in the real world, so now using a queue which will keep the data sorted for us on insertion and we can check the earliest timestamp with constant time.
**Checklist:**
=> perf: store log events sorted in a queue

pom.xml, uat/testing-features/src/main/java/com/aws/greengrass/steps/CloudWatchSteps.java, uat/testing-features/src/main/resources/greengrass/features/log-manager-1.feature
Add scenario T6 to test our upload speed over 200,000 log events for a single component.
This test shows that the current main branch can achieve ~1.6MBps which is compared to ~0.4MBps on the current release branch, proving that the changes are quite meaningful.
**Checklist:**
=> test(uat): add test for upload speed

pom.xml, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/main/java/com/aws/greengrass/logmanager/util/ConfigUtil.java, src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java, src/test/java/com/aws/greengrass/logmanager/util/ConfigUtilTest.java
1. Add new config option "deprecatedVersionSupport" which will prevent log manager from loading and writing the deprecated currently processing file information. This helps with performance because we don't need to write the same information to both the V2 section and the deprecated section. The default is to keep supporting the old version, set it to "false" to stop it.
2. Add a new ConfigUtil which allows updating config from a map, but ignoring when nothing actually changes. Currently a large portion of config updates are just "timestampUpdated" which we really don't care about.
Utilizing both of these changes, we're up to ~1.8MBps upload rate.
**Any additional …
=> perf: only write actually changed values to config

src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/main/java/com/aws/greengrass/logmanager/LogManagerService.java, src/main/java/com/aws/greengrass/logmanager/model/LogFile.java
Handle `ClosedByInterruptException` instead of only `IOException` to avoid unhelpful logs at too high of a level.
**Checklist:**
=> fix: catch ClosedByInterruptException and handle it at debug/info

src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java, src/test/resources/com/aws/greengrass/logmanager/testlogs1.log, uat/custom-components/src/test/java/com/aws/greengrass/LogGeneratorTest.java
#213
Handle the case where log level is null in deserialized JSON format logs. Log level is never supposed to be null, so this should only be possible if someone is not using the Greengrass logger (waiting for more customer info to determine this). Regardless, we should handle the case properly. Here we default to INFO level if the log level parsed from JSON is null or empty.
Updated existing test file with a null log level and verified that test fails without the fix and that it passes with the fix.
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> fix: handle valid JSON messages which are not GreengrassLogMessages

.github/workflows/externalPR.yml, .github/workflows/maven.yml, .github/workflows/uat.yaml
=> ci: upgrade github actions

src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java
=> fix: sanity check startPosition

src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java, src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java, src/main/java/com/aws/greengrass/logmanager/CloudWatchLogsUploader.java, src/main/java/com/aws/greengrass/logmanager/util/CloudWatchClientFactory.java, src/main/java/com/aws/greengrass/logmanager/util/SdkClientWrapper.java, src/test/java/com/aws/greengrass/logmanager/CloudWatchLogsUploaderTest.java
Add sdk client wrapper for all API calls through cloudwatch sdk client
Under network unstable, the sdk client retried an http call, however, some of the times the client will try to use a connection which already being closed but the connection was not aware which makes the retry happens infinitely even after the network becomes stable. To address this, we would like to create a mechanism to force refresh the client when certain exceptions got thrown
Unit test
**Checklist:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> fix: add client wrapper

src/main/java/com/aws/greengrass/logmanager/util/SdkClientWrapper.java
Ignoring cases and white spaces
**Checklist:**
=> fix: ignore cases
