- README.md
Also make minor changes to the YAML example.
**Checklist:**
> docs: Add JSON configuration example in README.

- pom.xml
- src/integrationtests/java/com/aws/greengrass/logmanager/LogManagerTest.java
- src/integrationtests/java/com/aws/greengrass/logmanager/SpaceManagementTest.java
- src/main/java/com/aws/greengrass/logmanager/CloudWatchLogsUploader.java
- src/main/java/com/aws/greengrass/logmanager/util/CloudWatchClientFactory.java
- src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java
- src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
> feat: support network proxy settings

- src/main/java/com/aws/greengrass/logmanager/CloudWatchLogsUploader.java
- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
> fix: avoid logging stacktrace for expected exceptions

- src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java
- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
- src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java
1. Make sure log stream name meets the CloudWatch requirement: length under 512 chars, and replacing illegal char ":" with "/"
1. Add default values for log file and directory names for components in Log Manager configuration to avoid NPE.
Unit test and end-to-end tests.
**Checklist:**
> fix: make sure log stream name meets the CloudWatch requirement

- pom.xml
> build: revert version to 2.1.0 because it is still binary compatible

- src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java
- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
Log file deletion at info level instead of debug.
Because it is a major operation and deserves more visibility.
**Checklist:**
> Delete file log level

- src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java
- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
Log file deletion action at info level instead of debug.
Because it is a major operation and deserves more visibility.
**Checklist:**
> fix: log file deletion at info level

- src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java
- src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java
* fix total chunk calculating logic to not introduce an extra chunk
* fix log line copy logic to copy correct chunk of log line instead
of always copy from the begining
There are 2 case for failure:
* If a log line is multiple times of `MAX_EVENT_LENGTH`, 1 empty log event will be created
* For over size log line, LogManager can only copy from the beginning of the line
This fix resolves the bugs
* Unit-tests covered
**Checklist:**
n
> fix: bugs resulting log events created incorrectly

- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
Updates log space-based deletion so that we only walk the directory once and then immediately attempt to delete files.
Catches all errors in the space management thread and reschedule it to run again if it fails for whatever reason. It was failing for some customers due to an unchecked io exception when getting the length of a file which no longer exists.
**Checklist:**
> fix: restart space management thread if it dies for some reason

- src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java
Clarifying comments for default multiLineStartPattern
**Checklist:**
> docs: clarify comments for default multiLineStartPattern

- src/main/java/com/aws/greengrass/logmanager/CloudWatchLogsUploader.java
Downgrade logging level for invalid sequence token, since it's expected when log manager restarts and uploads to an existing log stream for the first time.
**Checklist:**
> fix: downgrade logging level for invalid sequence token

- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
- src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
Does not store `currentProcessingFileInformation` when the filename is null or empty which should not ever happen. Synchronizes `currentComponentFileProcessingInformation` writing by running all of the writes in a single batch which should prevent any possibility for reads and writes overlapping.
**Checklist:**
> fix: address null filename stored in runtime configuration

- src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java
- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFile.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFileInformation.java
- src/test/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessorTest.java
- src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
- src/test/java/com/aws/greengrass/logmanager/model/LogFileTest.java
#51 
Add a class LogFile to include business logic, i.e. hash generation
This is one step of #51 , and it refines the code structure
Unittest
Can be merged but not ready for release.
**Checklist:**
- [ x] Updated or added new unit tests
> feat: add log file class with hash generation

- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
#51 
Refactor the current change so that we will iterate all components before processing each work
This will be used for future feature of uploading active file to avoid endless running into the same component.
Pass all current tests
**Checklist:**
> refactor: add unitOfWork

- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
- src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
#51 
Handle the upgrade scenarios for customer from older version. 
The fileHash does not exist in older version. And fileName is deprecated from older version. 
This will be tested in UAT
**Checklist:**
> feat: handle the upgrading from older version

- src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java
- src/test/java/com/aws/greengrass/logmanager/util/TestUtils.java
Fix flaky test that was just randomly sleeping and occasionally failing
> fix: fix flaky test

- pom.xml
> chore: temporarily lower coverage limits

- src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java
Add method to process a single open file rather than iterating over a list.
This is needed to prevent TOCTOU races.
**Checklist:**
> feat: process single log file

- pom.xml
- src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java
> feat: add getLogGroupName method

- src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerConfigTest.java
- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFile.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java
- src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
> refactor: process one file at a time

- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFile.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java
- src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
This reverts commit 82cea8bdbb3f99000011ddfc9e52b1a6778b7046.
**Checklist:**
> revert: "refactor: process one file at a time (#124)"

- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
> fix: skip the processed file then re-read it

- src/main/java/com/aws/greengrass/logmanager/CloudWatchAttemptLogsProcessor.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFile.java
> chore: remove unused channel methods

- src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java
Earlier static hashmap was used which got initialized for every component  log group resulting in overridden hashmap. This change ties the hashmap to the component log group as an attribute. 
From this PR - https://github.com/aws-greengrass/aws-greengrass-log-manager/pull/136
**Checklist:**
> fix: use component specific map to store hashes

- src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java
- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java
- src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
> chore: remove syncDirectory method

- src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/LogManagerTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/logmanager/SpaceManagementTest.java
- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
- src/main/java/com/aws/greengrass/logmanager/model/LogFileGroup.java
- src/test/java/com/aws/greengrass/logmanager/LogManagerServiceTest.java
- src/test/java/com/aws/greengrass/logmanager/model/LogFileGroupTest.java
> chore: plumb work directory to LogFileGroup

- src/main/java/com/aws/greengrass/logmanager/model/LogFile.java
Tiny change to avoid unnecessary  IO operations to compute the hash.
Manual tests. We will add more tests in a subsequent PR
> refactor: memoize hash string value

- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
Given we are uploading the active file it can happen that we catch up uploading all the contents on the active log file and we record the start position as the length of the file. Then it gets rotated before the next cycle starts becoming now a rotated file and not getting deleted.
This PR ensure we delete the previous active file when it gets rotated
> fix: delete rotated active file

- .github/workflows/maven.yml
Build UAT project when changes are pushed
> feat: build uats as part of github action build so it runs checkstyle and pmd checks

- uat/README.md
Update the README under uats to better describe what they do and how to run them
> chore: update readme for release

- src/main/java/com/aws/greengrass/logmanager/LogManagerService.java
- src/main/java/com/aws/greengrass/logmanager/services/DiskSpaceManagementService.java
This is the first step in improving how we handle the disk space management logic. Before making any change in behaviour I am extracting the disk space management code into its own class for testability and also making the change self contained given the LogManagerService class is already bloated.
Make the rework process easier given all the related code on the space management is in a single place.
Refactoring, no new code just a reorg, tests passing
> refactor: disk space management logic

- .github/workflows/uat.yaml
- README.md
Add the test result badges to the repo and run the UATs on push to branch main
Visibility of testing
> docs: display tests status

- uat/testing-features/src/main/java/com/aws/greengrass/steps/CloudWatchSteps.java
- uat/testing-features/src/main/java/com/aws/greengrass/steps/FileSteps.java
- uat/testing-features/src/main/resources/greengrass/features/log-manager-1.feature
Modify most UATs to verify the contents of the log files that were uploaded by using the log generator component
Ensure that making code changes do not break the Log Manager functionality
UATs
> test: check cw logs where applicable

- .github/workflows/codeql.yml
- .github/workflows/maven.yml
update deprecated github workflow actions version
**Checklist:**
> fix: bump github workflow actions version
